version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: hulkcao@123
       MYSQL_DATABASE: wordpress
       MYSQL_USER: hulkcao
       MYSQL_PASSWORD: hulkcao@123

   adminer:
       image: adminer
       ports:
            - 8080:8080

   wordpress_tls:
     depends_on:
       - db
     build: ./wordpress_tls
     ports:
       - '80:80'
       - '443:443'
     restart: always
     volumes:
       - ./wp-app:/var/www/html # Full wordpress project
       - ./letsencrypt_data:/etc/letsencrypt
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: hulkcao
       WORDPRESS_DB_PASSWORD: hulkcao@123
